Feature/cleaner builds and usb stuff
arduino-cmake/arduino-cmake pull request #35
Opened 2017-12-15 06:35 UTC by fraillt

## Features
- new public function *override_usb_properties* to be able to customise USB defines for the board.

## Build improvements
- Added *CMAKE_CXX_STANDARD 11* required for USB support. Also added *-fno-threadsafe-statics* for CXX targets, because in C++11 static initialization is thread-safe, and compiler generates lock guards, which are not supported. This flag disables lock guards. We're in single thread anyway:)
- BoardFlags reworked. Created separate functions to use with recommended CMake functions, e.g. target_compile_options:
  -	_get_arduino_version_define - gets arduino version, requried for ARDUINO define.
  -	_get_board_compile_defines - list of defines, additionally added ARDUINO_<board_name> ARDUINO_ARCH_AVR USB_PRODUCT and USB_MANUFACTURER flags, they are used by some arduino libraries.
  -	_get_board_compile_options - list of options
  -	_get_board_compile_includes - list of includes
  -	_set_board_compile_flags, _set_board_link_flags - instead of returning compile options and later using depreceted CMAKE function *set_target_properties*, directly sets flags to target using non depreceted functions.
- Removed ARDUINO_LIBRARIES_PATH and ARDUINO_PLATFORM_LIBRARIES_PATH includes, they are totally unnecessary, because we need explicit path for each library that we get from *find_arduino_library* function.
- Some internal function signature has changed during refactoring.
  -	make_arduino_library - removed COMPILE_FLAGS and LINK_FLAGS parameters, and instead of returing one parameter now returns two parameters explicitly (LIB_TARGETS, LIB_INCLUDES)
  -	make_arduino_libraries - removed not used SRCS, COMPILE_FLAGS, LINK_FLAGS and instead added ARD_LIBS_PATH, and also returns two parameters explicitly (LIB_TARGETS, LIB_INCLUDES)
  -	create_arduino_target - removed unused LINK_FLAGS
- updated compiler flags for C, CXX and ASM (new)
- new internal function *_override_board_property*, used to override values loaded from boards.txt.

These changes now enable to use boards with USB (leonardo, micro, one ... ).
#4 can be solved by using new public function *override_usb_properties*
#32 should just work.

@MrPointer and @JonasProgrammer could you please help me to find a better place for *override_usb_properties* function?
Currently I added it in Platform\Core\BoardPropertiesReader.cmake. 
I was thinking maybe it would make sense to create a different folder to store all public/user functions, it would be easier to find out if a function can change its signature without breaking users code.

2017-12-16 20:36 UTC, MrPointer commented
I don't have time to review this completely right now, I will try to tackle it in a few days, sorry.

2017-12-18 23:07 UTC, Baycken commented
OK I tested the setting VID and PID for Arduino Leonardo and here is my results:

SoftwareSerial library seems to cause the Leonardo to hang (related to the PR, but interesting to look into).

So, to test the code, I used the blink sketch, and run into the issue of the cmake unable to properly parse the arduino verision, and try to source `WProgram.h`.

This is fixed by sourcing `Arduino.h` directly without the defines I was able to get it to work without the `FORCE` option.
This is the flag.make without `FORCE`:
```
CXX_DEFINES = -DARDUINO="1            0            5" -DARDUINO_ARCH_AVR -DARDUINO_AVR_LEONARDO -DF_CPU=16000000L -DUSB_MANUFACTURER="\"My Board Factory\"" -DUSB_PID=0x4567 -DUSB_PRODUCT="\"Tamagotchi Pet\"" -DUSB_VID=0x1234
```
This is the flag.make with `FORCE`:
```
CXX_DEFINES = -DARDUINO="1            0            5" -DARDUINO_ARCH_AVR -DARDUINO_AVR_LEONARDO -DF_CPU=16000000L -DUSB_MANUFACTURER=\"Unknown\" -DUSB_PID=0x8036 -DUSB_PRODUCT="\"Arduino Leonardo\"" -DUSB_VID=0x2341
```

As seen, the force option is not working as intended, the ARDUNO flag is not set properly, and the escape for the `USB_MANUFACTUER` is wrong as well.

Lastly, it seems that USB property override are on a per board basis, would it be possible to make it per executable? Since the whole reasoning behind this feature is to have unique PID and VID per executable?

2017-12-19 07:38 UTC, fraillt commented
`ARDUINO` define was released in 2.0.0 so I made a hotfix PR to fix it.
Regarding `USB_MANUFACTURER` why do you think  is wrong? It is perfectly fine `-DUSB_MANUFACTURER=\"Unknown\"` and `-DUSB_MANUFACTURER="\"My Board Factory\""` are good values, When an expression is separated by space, additional quotes are added. e.g. `-DARDUINO=105` becames `-DARDUINO="1 0 5"`
Regarding `FORCE` options, it seems that you didn't clear your CMake cache... This functionality overrides values in the cache, and without `FORCE` options you shouldn't be able to set `USB_MANUFACTURER` for leonardo board, because it doesn't have this flag in `boards.txt`. 
But one thing is wrong in this example, this `OVERRIDE_USB_PROPERTIES` should be before `GENERATE_ARDUINO_FIRMWARE` because it first must override values in the cache before they are used.
Regarding your request to make this per executable, instead of per board, it is not so easy.
In order do to this, we need different Arduino libraries for different executables. e.g. if you have 3 leonardo board executables, we need 3 different leonardo cores and 3x all other additional libraries. Currently, we don't have this functionality, it is a perfect place for you to contribute :) 
As I see it, we could solve this by having some configuration context, and then pass that context to each function that we currently have. To make it non breaking change, there could always exist a default context.

2017-12-21 17:21 UTC, MrPointer commented
Finally I can relate.
As @noseglasses mentioned in one of his comments in #38, **it is a monster**. In fact, it's quite surprising to see such a big PR after we've already talked about this in #29 - There's no point in compressing all those changes into a single PR as no one, including yourself, can tell how each feature affects the rest of the system.
I will **not** accept this PR until it's separated into separated features, just as @noseglasses did with his (Everyone can be inspired by his work). However, I'll try to help you once again to do it:
* *BoardFlags reworked* - Accept for one sub-feature you've listed there regarding USB, I don't think there's need to couple it with USB-support.
* *Removed ARDUINO_LIBRARIES_PATH and ARDUINO_PLATFORM_LIBRARIES_PATH includes* - Have nothing to do with USB-support, more like a bug-fix which should be discussed separately.
* *Some internal function signature has changed* - Again, should be discussed on a separate PR.
* *updated compiler flags* - Yet again.
Notice that I didn't point out any USB-related features - Those should just "remain" in a similar PR dedicated to USB-support.
Thank you for all your contribution, and I hope we'll be able to merge your work ASAP!

2017-12-28 22:11 UTC, MrPointer requested changes
**Note:** I've already posted this comment but I didn't notice it wasn't a review. It is now :)
Finally I can relate.
As @noseglasses mentioned in one of his comments in #38, it is a monster. In fact, it's quite surprising to see such a big PR after we've already talked about this in #29 - There's no point in compressing all those changes into a single PR as no one, including yourself, can tell how each feature affects the rest of the system.
I will not accept this PR until it's separated into separated features, just as @noseglasses did with his (Everyone can be inspired by his work). However, I'll try to help you once again to do it:

BoardFlags reworked - Accept for one sub-feature you've listed there regarding USB, I don't think there's need to couple it with USB-support.
Removed ARDUINO_LIBRARIES_PATH and ARDUINO_PLATFORM_LIBRARIES_PATH includes - Have nothing to do with USB-support, more like a bug-fix which should be discussed separately.
Some internal function signature has changed - Again, should be discussed on a separate PR.
updated compiler flags - Yet again.
Notice that I didn't point out any USB-related features - Those should just "remain" in a similar PR dedicated to USB-support.
Thank you for all your contribution, and I hope we'll be able to merge your work ASAP!

2025-01-01 21:10 UTC, closed without merging