Allow ommitting mcu
arduino-cmake/arduino-cmake pull request #39
Opened 2017-12-20 11:54 UTC by noseglasses

This PR enables simulated builds of firmware in an x86 environment, e.g. for regression testing.
gcc for x86 cannot deal with `-mmcu=...` definitions. Thus we only set them, if the respective board property is defined.

2017-12-20 12:08 UTC, fraillt commented
Can you describe in more details your flow, how do you simulate in the x86 environment? do you create a fake board in `boards.txt` file?
Could you explain this process step-by-step it would be helpful to know your process and maybe we could add explicit support for it in library instead of hacking something :)

2017-12-20 12:46 UTC, noseglasses commented
Please checkout this https://github.com/keyboardio/Kaleidoscope-Hardware-Virtual
It describes how this is setup to build a x86 binary of a firmware using arduino-builder.

This PR is one of a series that moves towards supporting the same with Arduino-CMake. 
As I do not like huge PRs so I split everything up into simple chunks.

2017-12-20 13:04 UTC, fraillt commented
Ok, thanks for your info.
But this is not a correct way of handling this problem.
Problem is not with the `mcu` flag, but this project simple doesn't handle customized build process, that is written in `platform.txt` file. What you're trying to do with Kaleidoscope-Hardware-Virtual project is the same as #34 we need a general way to implement build process that works as written in `platform.txt`.

2017-12-20 13:05 UTC, fraillt requested changes
We need to address this issue in a general way by supporting customized build process #34

2017-12-20 13:29 UTC, noseglasses commented
I would love to have a more general way of addressing this but as long as there is none, my PR makes things work and does not break anything. So I don't see any problems with a temporary fix.

2017-12-21 17:28 UTC, MrPointer submitted a review, later dismissed
I do agree with @fraillt that we need something better to customize the build process, however this change truly doesn't hurt anybody - It's very lightweight and simple, and as @noseglasses pointed out, solves the problem temporarily.

2017-12-21 20:46 UTC, MrPointer requested changes
As my review in #40, this change should be merged to the `develop` branch instead. In this case it's clear since it's a feature, not even a bug fix.
To avoid such wasted PRs in the future, please relate to the [Contribution](https://github.com/arduino-cmake/arduino-cmake/blob/master/CONTRIBUTING.md) file.
Could you PR it to `develop` instead?

2017-12-22 15:15 UTC, noseglasses commented
This is continued in #44

2017-12-22 15:15 UTC, closed without merging